PREDMET_INFO = """
<PREDMET_INFO>
 <FAKULTA_ID>101</FAKULTA_ID>
 <FAKULTA_ZKRATKA_DOM>fi</FAKULTA_ZKRATKA_DOM>
 <KOD_PREDMETU>PB161</KOD_PREDMETU>
 <KRATKY_NAZEV_PREDMETU>Programování v jazyce C++</KRATKY_NAZEV_PREDMETU>
 <KRATKY_NAZEV_PREDMETU_ANGL>C++ Programming</KRATKY_NAZEV_PREDMETU_ANGL>
 <NAZEV_PREDMETU>Programování v jazyce C++</NAZEV_PREDMETU>
 <NAZEV_PREDMETU_ANGL>C++ Programming</NAZEV_PREDMETU_ANGL>
 <NEVYPISUJE_SE>0</NEVYPISUJE_SE>
 <OBDOBI_ID>6383</OBDOBI_ID>
 <OBDOBI_NAZEV>podzim 2015</OBDOBI_NAZEV>
 <OBDOBI_NAZEV_ANGL>Autumn 2015</OBDOBI_NAZEV_ANGL>
 <OBDOBI_ZKRATKA_PRO_URL>podzim2015</OBDOBI_ZKRATKA_PRO_URL>
 <OBDOBI_ZKRATKA_PRO_URL_ANGL>autumn2015</OBDOBI_ZKRATKA_PRO_URL_ANGL>
 <POCET_ZAPSANYCH_STUDENTU>174</POCET_ZAPSANYCH_STUDENTU>
 <POCET_ZAREG_STUDENTU>180</POCET_ZAREG_STUDENTU>
 <PREDMET_ID>869944</PREDMET_ID>
 <SEMINARE>
  <SEMINAR>
   <LIMIT_ID>365290</LIMIT_ID>
   <LIMIT_LZE_SDILET>ne</LIMIT_LZE_SDILET>
   <MAX_STUDENTU>15</MAX_STUDENTU>
   <NASOBNE_PRIHLASENI>ne</NASOBNE_PRIHLASENI>
   <ODHLASIT_DO>20151004000000</ODHLASIT_DO>
   <OZNACENI>01</OZNACENI>
   <POCET_STUDENTU_VE_SKUPINE>15</POCET_STUDENTU_VE_SKUPINE>
   <PORADI/>
   <POZNAMKA/>
   <PRIHLASIT_DO>20151004000000</PRIHLASIT_DO>
   <PRIHLASIT_OD>20150901180000</PRIHLASIT_OD>
   <SEMINAR_ID>365290</SEMINAR_ID>
   <VCETNE_NEAKTIVNICH>ne</VCETNE_NEAKTIVNICH>
   <ZMENENO>20150819215850</ZMENENO>
   <ZMENIL>118152</ZMENIL>
  </SEMINAR>
 </SEMINARE>
 <VYUCUJICI_SEZNAM>
  <VYUCUJICI>
   <CELE_JMENO>Leoš Otáhal</CELE_JMENO>
   <JMENO>Leoš</JMENO>
   <OSOBA_TEXTOVE>ne</OSOBA_TEXTOVE>
   <PRIJMENI>Otáhal</PRIJMENI>
   <ROLE>přednášející</ROLE>
   <UCO>445324</UCO>
   <ZASTUPCE/>
  </VYUCUJICI>
  <VYUCUJICI>
   <CELE_JMENO>RNDr. Jaroslav Bayer</CELE_JMENO>
   <JMENO>Jaroslav</JMENO>
   <OSOBA_TEXTOVE>ne</OSOBA_TEXTOVE>
   <PRIJMENI>Bayer</PRIJMENI>
   <ROLE>přednášející</ROLE>
   <UCO>72873</UCO>
   <ZASTUPCE>
    <CELE_JMENO>Bc. Martina Durkošová</CELE_JMENO>
    <JMENO>Martina</JMENO>
    <PRIJMENI>Durkošová</PRIJMENI>
    <UCO>395879</UCO>
   </ZASTUPCE>
  </VYUCUJICI>
 </VYUCUJICI_SEZNAM>
</PREDMET_INFO>
"""
