PREDMET_INFO = """
<PREDMET_INFO>
 <FAKULTA_ID>101</FAKULTA_ID>
 <FAKULTA_ZKRATKA_DOM>fi</FAKULTA_ZKRATKA_DOM>
 <KOD_PREDMETU>PB161</KOD_PREDMETU>
 <KRATKY_NAZEV_PREDMETU>Programování v jazyce C++</KRATKY_NAZEV_PREDMETU>
 <KRATKY_NAZEV_PREDMETU_ANGL>C++ Programming</KRATKY_NAZEV_PREDMETU_ANGL>
 <NAZEV_PREDMETU>Programování v jazyce C++</NAZEV_PREDMETU>
 <NAZEV_PREDMETU_ANGL>C++ Programming</NAZEV_PREDMETU_ANGL>
 <NEVYPISUJE_SE>0</NEVYPISUJE_SE>
 <OBDOBI_ID>100</OBDOBI_ID>
 <OBDOBI_NAZEV>podzim 2015</OBDOBI_NAZEV>
 <OBDOBI_NAZEV_ANGL>Autumn 2015</OBDOBI_NAZEV_ANGL>
 <OBDOBI_ZKRATKA_PRO_URL>podzim2015</OBDOBI_ZKRATKA_PRO_URL>
 <OBDOBI_ZKRATKA_PRO_URL_ANGL>autumn2015</OBDOBI_ZKRATKA_PRO_URL_ANGL>
 <POCET_ZAPSANYCH_STUDENTU>110</POCET_ZAPSANYCH_STUDENTU>
 <POCET_ZAREG_STUDENTU>120</POCET_ZAREG_STUDENTU>
 <PREDMET_ID>123456</PREDMET_ID>
 <SEMINARE>
  <SEMINAR>
   <LIMIT_ID>111111</LIMIT_ID>
   <LIMIT_LZE_SDILET>ne</LIMIT_LZE_SDILET>
   <MAX_STUDENTU>15</MAX_STUDENTU>
   <NASOBNE_PRIHLASENI>ne</NASOBNE_PRIHLASENI>
   <ODHLASIT_DO>20151004000000</ODHLASIT_DO>
   <OZNACENI>01</OZNACENI>
   <POCET_STUDENTU_VE_SKUPINE>15</POCET_STUDENTU_VE_SKUPINE>
   <PORADI/>
   <POZNAMKA/>
   <PRIHLASIT_DO>20151004000000</PRIHLASIT_DO>
   <PRIHLASIT_OD>20150901180000</PRIHLASIT_OD>
   <SEMINAR_ID>12364</SEMINAR_ID>
   <VCETNE_NEAKTIVNICH>ne</VCETNE_NEAKTIVNICH>
   <ZMENENO>20150819215850</ZMENENO>
   <ZMENIL>123456888</ZMENIL>
  </SEMINAR>
 </SEMINARE>
 <VYUCUJICI_SEZNAM>
  <VYUCUJICI>
   <CELE_JMENO>Jan Mrkva</CELE_JMENO>
   <JMENO>Jan</JMENO>
   <OSOBA_TEXTOVE>ne</OSOBA_TEXTOVE>
   <PRIJMENI>Mrkva</PRIJMENI>
   <ROLE>přednášející</ROLE>
   <UCO>44411133</UCO>
   <ZASTUPCE/>
  </VYUCUJICI>
  <VYUCUJICI>
   <CELE_JMENO>RNDr. Mr. Rabbit</CELE_JMENO>
   <JMENO>Mr.</JMENO>
   <OSOBA_TEXTOVE>ne</OSOBA_TEXTOVE>
   <PRIJMENI>Rabbit</PRIJMENI>
   <ROLE>přednášející</ROLE>
   <UCO>11223344</UCO>
   <ZASTUPCE>
    <CELE_JMENO>What Ever</CELE_JMENO>
    <JMENO>What</JMENO>
    <PRIJMENI>Ever</PRIJMENI>
    <UCO>444333222</UCO>
   </ZASTUPCE>
  </VYUCUJICI>
 </VYUCUJICI_SEZNAM>
</PREDMET_INFO>
"""

BLOCKS_CONTENT = """
<BLOKY_OBSAH>
 <STUDENT>
  <OBSAH>25 bodů</OBSAH>
  <UCO>444111000</UCO>
  <ZMENENO>20160111104208</ZMENENO>
  <ZMENIL>444111222</ZMENIL>
 </STUDENT>
 <STUDENT>
  <NEMA_POZN_BLOK>1</NEMA_POZN_BLOK>
  <UCO>444111222</UCO>
 </STUDENT>
</BLOKY_OBSAH>
"""

COURSE_LIST_STUDENTS = """
<PREDMET_STUDENTI_INFO>
 <STUDENT>
  <CELE_JMENO>Mgr. Jan Hruska</CELE_JMENO>
  <JMENO>Jan</JMENO>
  <PRIJMENI>Hruska</PRIJMENI>
  <SEMINARE/>
  <STAV_STUDIA>aktivní</STAV_STUDIA>
  <STAV_ZAPISU>zapsáno</STAV_ZAPISU>
  <STUDENT_NEMA_SEMINAR>1</STUDENT_NEMA_SEMINAR>
  <STUDIA>
   <STUDIUM_IDENTIFIKACE>FI C-CV EL celoživ.</STUDIUM_IDENTIFIKACE>
  </STUDIA>
  <UCO>444555666</UCO>
  <UKONCENI>z</UKONCENI>
 </STUDENT>
 
 <STUDENT>
  <CELE_JMENO>Bc. Simon Mrkva</CELE_JMENO>
  <JMENO>Simon</JMENO>
  <PRIJMENI>Mrkva</PRIJMENI>
  <SEMINARE/>
  <STAV_STUDIA>aktivní</STAV_STUDIA>
  <STAV_ZAPISU>zapsáno</STAV_ZAPISU>
  <STUDENT_NEMA_SEMINAR>0</STUDENT_NEMA_SEMINAR>
  <STUDIA>
   <STUDIUM_IDENTIFIKACE>FI C-CV EL celoživ.</STUDIUM_IDENTIFIKACE>
  </STUDIA>
  <UCO>4445557777</UCO>
  <UKONCENI>z</UKONCENI>
 </STUDENT>
</PREDMET_STUDENTI_INFO>
"""

SEMINARY_LIST_STUDENTS = """
<SEMINAR_STUDENTI_INFO>
 <SEMINAR>
  <OZNACENI>01</OZNACENI>
  <SEMINAR_ID>11111111111</SEMINAR_ID>
  <STUDENT>
   <CELE_JMENO>What ever</CELE_JMENO>
   <JMENO>What</JMENO>
   <PRIJMENI>Ever</PRIJMENI>
   <STAV_STUDIA>ukončené</STAV_STUDIA>
   <STUDIA>
    <STUDIUM_IDENTIFIKACE>FI B-AP BcAP (abs.) (ukonč.)</STUDIUM_IDENTIFIKACE>
   </STUDIA>
   <UCO>4445557777</UCO>
   <UKONCENI>z</UKONCENI>
  </STUDENT>
 </SEMINAR>
 
 <SEMINAR>
  <OZNACENI>02</OZNACENI>
  <SEMINAR_ID>11111111112</SEMINAR_ID>
  <STUDENT>
   <CELE_JMENO>What ever</CELE_JMENO>
   <JMENO>What</JMENO>
   <PRIJMENI>Ever</PRIJMENI>
   <STAV_STUDIA>ukončené</STAV_STUDIA>
   <STUDIA>
    <STUDIUM_IDENTIFIKACE>FI B-AP BcAP (abs.) (ukonč.)</STUDIUM_IDENTIFIKACE>
   </STUDIA>
   <UCO>4445557777</UCO>
   <UKONCENI>z</UKONCENI>
  </STUDENT>
 </SEMINAR>
</SEMINAR_STUDENTI_INFO>
"""

SEMINARY_LIST_TEACHERS = """
<SEMINAR_CVICICI_INFO>
 <SEMINAR>
  <CVICICI>
   <CELE_JMENO>RNDr. Mgr. What ever</CELE_JMENO>
   <JMENO>What</JMENO>
   <PRIJMENI>Ever</PRIJMENI>
   <UCO>4445557777</UCO>
  </CVICICI>
  <OZNACENI>01</OZNACENI>
  <SEMINAR_ID>123456</SEMINAR_ID>
 </SEMINAR>
 
  <SEMINAR>
  <CVICICI>
   <CELE_JMENO>RNDr. Mgr. What ever</CELE_JMENO>
   <JMENO>What</JMENO>
   <PRIJMENI>Ever</PRIJMENI>
   <UCO>4445557777</UCO>
  </CVICICI>
  <OZNACENI>02</OZNACENI>
  <SEMINAR_ID>123457</SEMINAR_ID>
 </SEMINAR>
</SEMINAR_CVICICI_INFO>
"""

NOTES_LIST = """
<POZN_BLOKY_INFO>
 <POZN_BLOK>
  <BLOK_ID>5545421544412</BLOK_ID>
  <JMENO>Test X</JMENO>
  <NEDOPLNOVAT_CHYBEJICI_STUDIA>a</NEDOPLNOVAT_CHYBEJICI_STUDIA>
  <STUDENTOVI_ZOBRAZIT_STATISTIKU>a</STUDENTOVI_ZOBRAZIT_STATISTIKU>
  <STUDENT_SMI_NAHLIZET>a</STUDENT_SMI_NAHLIZET>
  <TYP_ID>1</TYP_ID>
  <TYP_NAZEV>obecný blok</TYP_NAZEV>
  <ZKRATKA>tst_x</ZKRATKA>
  <ZMENENO>20160112115151</ZMENENO>
  <ZMENIL>456698545255</ZMENIL>
 </POZN_BLOK>
</POZN_BLOKY_INFO>
"""
